version: "3.0"
services:
  redis:
    image: redis:7
    restart: always
    networks:
      - ns
  db:
    image: chat-api
    restart: always
    ports:
      - 9988:9988
    networks:
      - ns

networks:
  ns: